spring:
  application:
    name: reviewms
  config:
    import: "optional:file:.env[.properties]"  # Tells Spring Boot to import the .env file from the root directory

  datasource:
    url: ${RMS_DATABASE_URL}
    username: ${RMS_DATABASE_USERNAME}
    password: ${RMS_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    
    database-platform: org.hibernate.dialect.PostgreSQLDialect
 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

  rabbitmq:
    host: ${RMS_RABBITMQ_HOST}
    port: ${RMS_RABBITMQ_PORT}
    username: ${RMS_RABBITMQ_USERNAME}
    password: ${RMS_RABBITMQ_PASSWORD}